#!/bin/bash

brew install git-delta

cp ~/.gitconfig ~/.gitconfig.bkp

tee -a ~/.gitconfig  <<EOF

[core]
  pager = delta
  quotepath = false
  ignorecase=false

[interactive]
  diffFilter = delta --color-only

[add.interactive]
  useBuiltin = false # required for git 2.37.0

[delta]
  side-by-side = true # use splite view
  line-numbers = true # show line number
  navigate = true    # use n and N to move between diff sections
  light = false      # set to true if you're in a terminal w/ a light background color (e.g. the default macOS terminal)

[merge]
  conflictstyle = diff3

[diff]
    colorMoved = default

EOF