#!/bin/bash

echo ”install directory is {$HOME}”
read -p "ok? (y/N): " yn
case "$yn" in [yY]*) ;; *) echo "not install." ; exit ;; esac

echo "remove cached"
rm -rf $HOME/.dotnet
rm -rf $HOME/.nuget
rm -rf $HOME/dotnet

echo "install dotnet-sdk"

mkdir $HOME/dotnet

# https://github.com/dotnet/core/tree/main/release-notes
curl https://download.visualstudio.microsoft.com/download/pr/d506b3c6-5ba1-41c4-8c44-5eefa6095ad0/a95ac6a119735937f196b2b81d2351d3/dotnet-sdk-6.0.310-osx-arm64.tar.gz | tar xvf - -C $HOME/dotnet
curl https://download.visualstudio.microsoft.com/download/pr/4402413a-ef81-4732-a0c0-38f11694b226/e205b8bf48d95902a6dbe1c3cccca272/dotnet-sdk-7.0.202-osx-arm64.tar.gz | tar xvf - -C $HOME/dotnet

# echo 'export PATH="$HOME/dotnet:$PATH"' >> ~/.zshrc

