#!/bin/sh

# Get the current branch name
branch=$(git symbolic-ref --short HEAD)

# Define the disallowed branch names
disallowed_branches=("main" "master")

# Check if the branch name is in the disallowed list
for disallowed_branch in "${disallowed_branches[@]}"; do
  if [[ "$branch" == "$disallowed_branch" ]]; then
    echo "---Warning---"
    echo "You are committing on the '$branch' branch."
    echo "Are you sure you want to continue?"
    echo "(Enter 'yes' or 'no')"

    # Redirect standard input to read from the terminal
    exec </dev/tty

    read userInput
    if [[ "$userInput" != "yes" ]]; then
      echo "Commit aborted. Please confirm before committing on the '$branch' branch."
      exit 1
    fi
    break
  fi
done

# If the branch name is valid or user confirmed, allow the commit
exit 0